// One-time import of Leap_appointments_July.xlsx (the per-agent-tab workbook
// for July 2026). Unlike scripts/seed.ts, this is NOT safe to re-run: appt
// codes are auto-generated by the DB trigger rather than taken from the
// workbook (July's own Appt IDs restart at 0001 per sheet and collide with
// codes already used by the June CSV import), so running this twice would
// create duplicate appointments.
//
// Usage: npx tsx scripts/import-july-2026.ts [path-to-xlsx]

import { config } from "dotenv";
import { resolve } from "node:path";
import XLSX from "xlsx";
import { createClient } from "@supabase/supabase-js";

config({ path: resolve(process.cwd(), ".env.local") });

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!SUPABASE_URL || !SERVICE_ROLE_KEY) {
  throw new Error("Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.local");
}

const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
  auth: { autoRefreshToken: false, persistSession: false },
});

const BRANCH_NAME = "Main Showroom";

// sheet tab name -> profiles.username. Kanar's tab and the unhired Agent 8/9/10
// placeholders have no real rows and are skipped.
const SHEET_TO_USERNAME: Record<string, string> = {
  Haya: "haya",
  Rawand: "rawand",
  Eman: "eman",
  Suad: "suad",
  Salma: "salma",
};

const STATUS_MAP: Record<string, string> = {
  Scheduled: "scheduled",
  Confirmed: "confirmed",
  Attended: "attended",
  "No Show": "no_show",
  Rescheduled: "rescheduled",
  Cancelled: "cancelled",
  "Closed / Sold": "closed_sold",
};

const SOURCE_MAP: Record<string, string> = {
  "Phone Call": "phone_call",
  WhatsApp: "whatsapp",
};

// Excel's epoch is 1899-12-30 (to account for the classic 1900 leap-year bug).
function excelSerialToISODate(serial: number): string {
  const d = new Date(Date.UTC(1899, 11, 30) + Math.round(serial) * 86400000);
  return d.toISOString().slice(0, 10);
}

function excelFractionToTime(frac: number): string {
  const totalMinutes = Math.round(frac * 24 * 60);
  const h = Math.floor(totalMinutes / 60) % 24;
  const m = totalMinutes % 60;
  return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}`;
}

async function loadProfileIds(): Promise<Record<string, string>> {
  const { data, error } = await supabase.from("profiles").select("id, username");
  if (error) throw new Error(`Failed to load profiles: ${error.message}`);
  return Object.fromEntries((data ?? []).map((p) => [p.username, p.id]));
}

async function loadBranchId(): Promise<string> {
  const { data, error } = await supabase
    .from("branches")
    .select("id")
    .eq("name", BRANCH_NAME)
    .single();
  if (error || !data) throw new Error(`Branch "${BRANCH_NAME}" not found — run npm run seed first`);
  return data.id;
}

async function main() {
  const filePath = process.argv[2] ?? resolve(process.env.HOME!, "Downloads/Leap_appointments_July.xlsx");
  console.log(`Reading ${filePath}...`);
  const wb = XLSX.readFile(filePath);

  const profileIds = await loadProfileIds();
  const branchId = await loadBranchId();

  const appointments: Record<string, unknown>[] = [];

  for (const [sheetName, username] of Object.entries(SHEET_TO_USERNAME)) {
    const sheet = wb.Sheets[sheetName];
    if (!sheet) throw new Error(`Sheet "${sheetName}" not found in workbook`);
    const assignedId = profileIds[username];
    if (!assignedId) throw new Error(`No profile for username "${username}" — run npm run seed first`);

    const rows = XLSX.utils.sheet_to_json<unknown[]>(sheet, { header: 1, defval: "" });
    const dataRows = rows.slice(2).filter((r) => r[0] !== "" && r[0] !== undefined);

    for (const row of dataRows) {
      const [
        _apptId,
        bookedOn,
        _agent,
        customerName,
        phone,
        source,
        apptDate,
        apptTime,
        _branch,
        status,
        _outcomeDate,
        saleAmount,
        _linkedApptId,
        notes,
      ] = row as [
        string, number | string, string, string, string, string,
        number | string, number | string, string, string,
        string, number | string, string, string,
      ];

      const mappedStatus = status ? STATUS_MAP[status as string] : "scheduled";
      if (!mappedStatus) throw new Error(`Unknown status "${status}" in sheet ${sheetName}`);
      const mappedSource = SOURCE_MAP[source as string];
      if (!mappedSource) throw new Error(`Unknown source "${source}" in sheet ${sheetName}`);

      // A handful of rows have no Appt Date at all (customer hadn't
      // committed to one yet — e.g. "some Saturday" in the notes). Falling
      // through to Number("") would silently compute the Excel epoch
      // (1899-12-30) as a bogus "real" date, so fall back to Booked On
      // instead, and only give up if neither is present.
      if (apptDate === "" && bookedOn === "") {
        throw new Error(`Row for "${customerName}" in sheet ${sheetName} has neither an Appt Date nor a Booked On date`);
      }
      const apptDateISO = excelSerialToISODate(Number(apptDate !== "" ? apptDate : bookedOn));
      // Every row in a batch must set the same keys: Supabase's bulk insert
      // unions the keys across the array and fills any row missing a key
      // with an explicit NULL rather than falling through to the column
      // default, so omitting created_at per-row (when Booked On is blank)
      // intermittently violated the NOT NULL constraint. Always set a
      // concrete value instead, falling back to the appointment's own date.
      const createdAtISO = bookedOn !== "" ? excelSerialToISODate(Number(bookedOn)) : apptDateISO;

      appointments.push({
        // appt_code intentionally omitted — the DB trigger assigns the next
        // sequential code for this agent.
        customer_name: customerName,
        phone: phone || null,
        assigned_agent: assignedId,
        branch_id: branchId,
        source: mappedSource,
        appt_date: apptDateISO,
        appt_time: apptTime !== "" ? excelFractionToTime(Number(apptTime)) : null,
        status: mappedStatus,
        sale_amount: saleAmount ? Number(saleAmount) : null,
        notes: notes || null,
        created_by: assignedId,
        created_at: `${createdAtISO}T00:00:00Z`,
      });
    }

    console.log(`  ${sheetName} (${username}): ${dataRows.length} rows`);
  }

  console.log(`\nImporting ${appointments.length} appointments (fresh appt_codes, no upsert)...`);
  const CHUNK = 50;
  let imported = 0;
  for (let i = 0; i < appointments.length; i += CHUNK) {
    const chunk = appointments.slice(i, i + CHUNK);
    const { error } = await supabase.from("appointments").insert(chunk);
    if (error) throw new Error(`Failed to import chunk starting at row ${i}: ${error.message}`);
    imported += chunk.length;
    console.log(`  ${imported}/${appointments.length}`);
  }

  console.log("\nDone.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
